name: Publish NuGet Package

on:
  push:
    branches:
      - none

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Restore, Build & Pack
      run: |
        dotnet restore ./FieldForge.Shared/FieldForge.Shared.sln
        dotnet build ./FieldForge.Shared/FieldForge.Shared.sln -c Release --no-restore
        dotnet pack ./FieldForge.Shared/src/FieldForge.Shared/FieldForge.Shared.csproj -c Release --no-build -o ./nupkg

    - name: Push NuGet package
      run: |
        dotnet nuget push "./nupkg/*.nupkg" \
          --api-key ${{ secrets.NUGET_API_KEY }} \
          --source ${{ secrets.NUGET_SOURCE_URL }} \
          --skip-duplicate